name: Continuous Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        docker --version

    - name: Log in to AWS ECR
      env:
        AWS_REGION: 'us-east-1'
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-model-repo:${{ github.sha }} .

    - name: Push Docker image to ECR
      run: |
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-model-repo:${{ github.sha }}

    - name: Deploy Model to SageMaker
      env:
        AWS_REGION: 'us-east-1'
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      run: |
        aws sagemaker create-model --model-name my-model-${{ github.sha }} \
          --primary-container Image=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-model-repo:${{ github.sha }},ModelDataUrl=s3://my-model-data/path

        aws sagemaker create-endpoint-config --endpoint-config-name my-model-${{ github.sha }}-config \
          --production-variants VariantName=AllTraffic,ModelName=my-model-${{ github.sha }},InitialInstanceCount=1,InstanceType=ml.m5.large,InitialVariantWeight=1.0

        aws sagemaker update-endpoint --endpoint-name my-model-endpoint \
          --endpoint-config-name my-model-${{ github.sha }}-config
