name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Lint code with flake8
      run: |
        flake8 src/ --max-line-length=88 --ignore=E203,W503

    - name: Run unit tests
      run: |
        pytest tests/

    - name: Build and Test Kedro Pipelines
      run: |
        kedro build-pipeline
        kedro test-pipeline
